#!/bin/sh
cmd.exe /c "set ENABLE_TESTS=true && @call build.bat"
EXIT_CODE=$?

if [ $EXIT_CODE -eq 1 ]; then
    echo "Cannot commit with failed build. Commit with --no-verify to ignore."
    exit $EXIT_CODE
fi



cmd.exe /c "@call scripts/tests/run_tests.bat"
EXIT_CODE=$?

if [ $EXIT_CODE -eq 1 ]; then
    echo "Cannot commit with failing unit tests. Exit Code: $EXIT_CODE. Commit with --no-verify to ignore."
    exit $EXIT_CODE
fi

exit 0